name: CI

on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: |
          cd src
          poetry run flake8 .
          
  test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Create envfile
        run: |
          touch .env
          echo DB_HOST=localhost >> .env
          echo DB_PORT=5432 >> .env
          echo DB_USER=postgre >> .env
          echo DB_PASSWORD=admin >> .env
          echo DB_NAME=TestDataBase >> .env
          cat .env

      - name: Run pytest
        run: |
          poetry run pytest tests
